preserve_hierarchy: true

files:
  - source: /app/i18n/locales/en-US.json
    translation: /app/i18n/locales/%locale%.json
    languages_mapping: &anchor
      language:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        ja: ja-JP
        ko: ko-KR
        ru: ru-RU
        de: de-DE
        fr: fr-FR
        id: id-ID
  - source : /app/i18n/**/en-US.md
    translation : /app/i18n/**/%two_letters_code%.md
    languages_mapping: *anchor
